name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Format check
      run: cargo fmt --check   
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: "cobaltstrike-beacon-rust-windows-x64.exe"
        path: target/release/cobaltstrike-beacon-rust.exe

